version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      - mynetwork
    ports:
      - "5230:5230"  # Expose port for external access

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      - mynetwork
    depends_on:
      - server

networks:
  mynetwork:
    driver: bridge